import numpy as np
import matplotlib as mpl

# available cmaps
"""
Color list. An exhaustive list of colors can be retrieved from matplotlib
printing matplotlib.colors.CSS4_COLORS.keys().
"""

colors = [
    "black",
    "deepskyblue",
    "peru",
    "darkorchid",
    "darkgoldenrod",
    "teal",
    "dodgerblue",
    "brown",
    "darkslategrey",
    "turquoise",
    "lightsalmon",
    "plum",
    "darkcyan",
    "orange",
    "slategrey",
    "darkmagenta",
    "limegreen",
    "deeppink",
    "gold",
    "springgreen",
    "midnightblue",
    "green",
    "mediumpurple",
    "mediumvioletred",
    "dimgrey",
    "blueviolet",
    "lightskyblue",
    "darksalmon",
    "royalblue",
    "fuchsia",
    "mediumaquamarine",
    "mediumblue",
    "grey",
    "sienna",
    "mediumslateblue",
    "seagreen",
    "purple",
    "greenyellow",
    "darkviolet",
    "coral",
    "darkblue",
    "goldenrod",
    "lime",
    "cornflowerblue",
    "darkturquoise",
    "orangered",
    "cadetblue",
    "lightcoral",
    "skyblue",
    "mediumseagreen",
    "tomato",
    "blue",
    "pink",
    "olivedrab",
    "rosybrown",
    "darkseagreen",
    "orchid",
    "olive",
    "lightseagreen",
    "cyan",
    "dimgrey",
    "magenta",
    "darkolivegreen",
    "slateblue",
    "lightgreen",
    "navy",
    "indianred",
    "lawngreen",
    "sandybrown",
    "steelblue",
    "salmon",
    "hotpink",
    "darkgrey",
    "violet",
    "cornflowerblue",
    "snow",
    "peru",
    "dimgray",
    "lightyellow",
    "indianred",
    "palegoldenrod",
    "darkgrey",
    "mediumblue",
    "peachpuff",
    "hotpink",
    "green",
    "brown",
    "lightgoldenrodyellow",
    "mediumturquoise",
    "lightslategrey",
    "slateblue",
    "purple",
    "lemonchiffon",
    "orchid",
    "darkred",
    "chocolate",
    "aquamarine",
    "cadetblue",
    "thistle",
    "orange",
    "darkkhaki",
    "yellowgreen",
    "lightsalmon",
    "lightsteelblue",
    "olivedrab",
    "mediumorchid",
    "papayawhip",
    "lime",
    "gainsboro",
    "teal",
    "coral",
    "lightslategray",
    "cyan",
    "lightgrey",
    "honeydew",
    "mediumvioletred",
    "chartreuse",
    "slategray",
    "steelblue",
    "gray",
    "orangered",
    "mediumseagreen",
    "aqua",
    "rebeccapurple",
    "saddlebrown",
    "lawngreen",
    "powderblue",
    "darkseagreen",
    "red",
]
cmap = mpl.colors.ListedColormap(colors)
boundaries = np.arange(len(colors) + 1) - 1.5
norm = mpl.colors.BoundaryNorm(boundaries, cmap.N, clip=True)

l = len(colors)

vcmap = "plasma"
vnorm = mpl.colors.Normalize(vmin=0.0, vmax=1.0)
