# This file is part of SliceRL by M. Rossi
gpu: "0"
dataset:
  split: 0.9
model:
  net_type: CMA # FF | CMA
  batch_size: 32
  test_batch_size: 32
  f_dims: 5 # 56 | 6
  use_bias: true
  threshold: 0.5
test:
  fn:
    - data/prod4_train/prova.csv.gz
    # - data/prod4_test/prod4_0.3GeV_run47144279_50evts.csv.gz
    # - data/prod4_test/prod4_0.5GeV_run47144284_50evts.csv.gz
    # - data/prod4_test/prod4_1GeV_run18800650_50evts.csv.gz
    # - data/prod4_test/prod4_2GeV_run44833767_50evts.csv.gz
    # - data/prod4_test/prod4_6GeV_run44121960_50evts.csv.gz
    # - data/prod4_test/prod4_7GeV_run20915159_50evts.csv.gz
  nev: 1
  min_hits: 5
  cthreshold:
      - 50
      - 20
train:
  fn:
    # - data/prod4_train/prova.csv.gz
    - data/prod4_train/prod4_0.3GeV_run47144279_100evts.csv.gz
    # - data/prod4_train/prod4_0.5GeV_run4714428_100evts.csv.gz
    # - data/prod4_train/prod4_1GeV_run18800650_0006_100evts.csv.gz
    # - data/prod4_train/prod4_2GeV_run44833767_100evts.csv.gz
    # - data/prod4_train/prod4_p6GeV_run44121960_100evts.csv.gz
    # - data/prod4_train/prod4_7GeV_run20915159_100evts.csv.gz
  nev: 5
  min_hits: 10
  hist_freq: 1
  loss: xent # xent | hinge | dice
  epochs: 50
  lr: 0.001
  min_lr: 0.00001
  patience: 15
  es_patience: 50
  optimizer: Adam
  initial_weights: null
scan: false
cluster:
  max_evals: 10
  enable: false
  url: null
  exp_key: null
