# This file is part of SliceRL by M. Rossi
gpu: "0"
dataset:
  split: 0.9
model:
  net_type: CM # DRB | RandLA | CM
  f_dims: 25
  use_bias: true
  threshold: 0.5
test:
  fn: data/exp_dir/new_set_03GeV.csv.gz
  nev: -1
  min_hits: 10
train:
  fn:
    - data/exp_dir/new_set_05GeV.csv.gz
    - data/exp_dir/new_set_1GeV.csv.gz
    - data/exp_dir/new_set_2GeV.csv.gz
    - data/exp_dir/new_set_3GeV.csv.gz
    - data/exp_dir/new_set_6GeV.csv.gz
    - data/exp_dir/new_set_7GeV.csv.gz
  nev: -1
  min_hits: 10
  hist_freq: 10
  loss: xent # xent | hinge | dice
  epochs: 100
  lr: 0.005
  min_lr: 0.00001
  patience: 15
  optimizer: Adam
  initial_weights: null
scan: false
cluster:
  max_evals: 10
  enable: false
  url: null
  exp_key: null
