# This file is part of SliceRL by M. Rossi
gpu: "0"
dataset:
  split: 0.9
model:
  net_type: CM # DRB | RandLA | CM
  batch_size: 32
  test_batch_size: 32
  f_dims: 56
  use_bias: true
  threshold: 0.5
test:
  fn:
    - data/pfo/prod4.csv.gz
  nev: -1
  min_hits: 50
train:
  fn:
    - data/pfo/prova.csv.gz
  nev: 3
  min_hits: 50
  hist_freq: 10
  loss: dice # xent | hinge | dice
  epochs: 1
  lr: 0.005636993511552649
  min_lr: 0.00001
  patience: 15
  es_patience: 50
  optimizer: Adam
  initial_weights: null
scan: false
cluster:
  max_evals: 10
  enable: false
  url: null
  exp_key: null
