# This file is part of SliceRL by M. Rossi
gpu: "0"
dataset:
  split: 0.9
  augment: false
model:
  net_type: SEAC # DRB | RandLA
  nb_classes: 128
  K: 64
  locse_nb_layers: 3
  use_bias: true
  threshold: 0.9
test:
  fn: data/def_dir/test_data_03GeV.csv.gz
  nev: -1
  min_hits: 300
train:
  fn:
    - data/def_dir/test_data_05GeV.csv.gz
    - data/def_dir/test_data_1GeV.csv.gz
    - data/def_dir/test_data_2GeV.csv.gz
    - data/def_dir/test_data_3GeV.csv.gz
    - data/def_dir/test_data_6GeV.csv.gz
    - data/def_dir/test_data_7GeV.csv.gz
  nev: -1
  min_hits: 300
  hist_freq: 1
  loss: xent # xent | hinge
  epochs: 50
  lr: 0.05
  min_lr: 0.00001
  patience: 5
  optimizer: Adam
  initial_weights: null
scan: false
cluster:
  max_evals: 10
  enable: false
  url: null
  exp_key: null
