# This file is part of SliceRL by M. Rossi
gpu: "0,1"
dataset:
    split: 0.9
model:
    net_type: DRB # DRB | RandLA
    fc_type: conv
    nb_classes: 128
    K: 16
    scale_factor: 3
    nb_layers: 2
    dropout: 0.1
    use_bias: true
test:
    fn: data/test_data_03GeV.csv.gz
    nev: -1
    min_hits: 1
train:
    fn:
    - data/test_data_05GeV.csv.gz
    - data/test_data_1GeV.csv.gz
    - data/test_data_2GeV.csv.gz
    - data/test_data_3GeV.csv.gz
    - data/test_data_6GeV.csv.gz
    - data/test_data_7GeV.csv.gz
    nev: -1
    min_hits: 1
    hist_freq: 1
    loss: xent # xent | focal | xent_l1 | focal_l1
    from_logits: True
    wgt: 50
    gamma: 2
    epochs: 50
    lr: 0.005
    min_lr: 0.00001
    patience: 5
    optimizer: Adam
    initial_weights: null # "initial_net.h5"
scan: false
cluster:
    max_evals: 10
    enable: false
    url: null
    exp_key: null