# This file is part of SliceRL by M. Rossi
gpu: "0"
dataset:
  split: 0.9
model:
  net_type: CM
  batch_size: hp.quniform("batch_size", 8, 32, 4)
  f_dims: 26
  use_bias: true
  threshold: 0.5
test:
  fn: data/exp_dir/new_set_03GeV.csv.gz
  nev: -1
  min_hits: 10
train:
  fn:
    - data/exp_dir/new_set_05GeV.csv.gz
    - data/exp_dir/new_set_1GeV.csv.gz
    - data/exp_dir/new_set_2GeV.csv.gz
    - data/exp_dir/new_set_3GeV.csv.gz
    - data/exp_dir/new_set_6GeV.csv.gz
    - data/exp_dir/new_set_7GeV.csv.gz
  nev: -1
  min_hits: 10
  hist_freq: 10
  loss: hp.choice("loss", ["xent", "dice"]) # xent | hinge | dice
  epochs: 150
  lr: hp.loguniform("lr", -10, -2)
  min_lr: 0.00001
  patience: 15
  es_patience: 50
  optimizer: hp.choice("optimizer", ["Adam", "SGD", "RMSprop", "Adagrad"])
  initial_weights: null
scan: true
cluster:
  max_evals: 200
  enable: false
  url: null
  exp_key: null
