# This file is part of SliceRL by M. Rossi
gpu: "0"
dataset:
    split: 0.9
    augment: false
model:
    net_type: SEAC
    use_bnorm: true
    use_ggf: hp.choice("ggf", [True, False])
    fc_type: conv
    nb_classes: 128
    K: hp.quniform("K", 16, 32, 2)
    scale_factor: hp.choice("scale_factor", [2,3,4])
    nb_layers: hp.choice("nb_layers", [2,3,4])
    nb_final_convs: hp.chioce("nb_final_convs", [1,2,3,4])
    dropout: hp.uniform("dropout", 0.1, 0.5)
    use_bias: hp.choice("use_bias", [True, False])
test:
    fn: data/test_data_03GeV.csv.gz
    nev: -1
    min_hits: 1
train:
    fn:
    - data/test_data_05GeV.csv.gz
    - data/test_data_1GeV.csv.gz
    - data/test_data_2GeV.csv.gz
    - data/test_data_3GeV.csv.gz
    - data/test_data_6GeV.csv.gz
    - data/test_data_7GeV.csv.gz
    nev: -1
    min_hits: 1
    split: 0.9
    hist_freq: 1
    loss: xent
    from_logits: true
    wgt: 50
    gamma: 2
    epochs: 30
    lr: hp.loguniform("lr", -10, -2)
    min_lr: 0.00001
    patience: 5
    optimizer: hp.choice("optimizer", ["Adam", "SGD", "RMSprop", "Adagrad"])
    initial_weights: null
scan: true
cluster:
    max_evals: 100
    enable: false
    url: null
    exp_key: null