# This file is part of SliceRL by M. Rossi
gpu: "0,1"
dataset:
    split: 0.9
model:
    fc_type: "conv"
    nb_classes: 128
    K: hp.quniform("K", 16, 32, 2)
    scale_factor: hp.choice("scale_factor", [2,3,4])
    nb_layers: hp.choice("nb_layers", [2,3,4])
    dropout: hp.uniform("dropout", 0.1, 0.5)
test:
    fn: "data/test_data_03GeV.csv.gz"
    nev: 2
    min_hits: 1
train:
    fn:
    - "data/test_data_05GeV.csv.gz"
    # - "data/test_data_1GeV.csv.gz"
    # - "data/test_data_2GeV.csv.gz"
    # - "data/test_data_3GeV.csv.gz"
    # - "data/test_data_6GeV.csv.gz"
    # - "data/test_data_7GeV.csv.gz"
    nev: 2
    min_hits: 1
    split: 0.9
    hist_freq: 1
    loss: "xent"
    from_logits: True
    wgt: 50
    gamma: 2
    epochs: 2
    lr: hp.loguniform("lr", -10, -2)
    min_lr: 0.00001
    patience: 5
    optimizer: hp.choice("optimizer", ["Adam", "SGD", "RMSprop", "Adagrad"])
    initial_weights: ""
scan: true
cluster:
    max_evals: 2
    enable: false
    url: null
    exp_key: null